{{- if .Values.tomcat.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-tomcat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-tomcat
  minReplicas: {{ .Values.tomcat.hpa.minReplicas }}
  maxReplicas: {{ .Values.tomcat.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.tomcat.hpa.cpuThreshold }}
{{- end }}
