{{- if .Values.alloy.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  labels:
    app: alloy
spec:
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      serviceAccountName: alloy
      containers:
      - name: alloy
        image: "{{ .Values.alloy.image.repository }}:{{ .Values.alloy.image.tag }}"
        args:
        - run
        - /etc/alloy/config.alloy
        - --server.http.listen-addr=0.0.0.0:12345
        - --storage.path=/var/lib/alloy/data
        ports:
        - containerPort: 12345
          name: http
        volumeMounts:
        - name: config
          mountPath: /etc/alloy
        - name: varlog
          mountPath: /var/log
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: alloy-config
      - name: varlog
        hostPath:
          path: /var/log
{{- end }}
